### PR TITLE
Updated the README with information about supported Serial Consoles

### PR DESCRIPTION
**Pull request by mileswdavis**
Attempted to provide some information about our findings when hunting for a serial adapter that would work.

### CODE REVIEW

**Comment by mileswdavis** [comment]
Hmmm. Looks like my markdown editor got a little handsy with more than I intended to touch. Let me know if you want me to back this out and resubmit without as much ... handsy.

**Comment by Pack3tL0ss** [comment]
I need to take a look at the documentation.  I may pull this in, but may move things around after.  I previously had the opposite... I had a page that listed adapters known not to have a serial #.  Most should if it's an FTDI chip, but it's up to the vendor that sourced the chip.  I do note that I recommend FTDI because they have a tool (FTPROG) that allows the user to create/change the serial number on the adapter, so about any adapter with a legit FTDI chipset, shouldn't be an issue.  Need to verify I have that in the readme, it may be noted in the info I display in the "predicable adapter ports" section of the installer.  Listing all the various vendors that sell adapters (especially when you get into the generic Chinese adapters) seemed cumbersome.  I had 1 or 2 that were not FTDI and did not have a serial or any way to do anything about it, but it wasn't that useful / hard to identify... generic no identifying model # or anything, and it's old so no valid online links. 

I'll review once I get a chance to see what makes the most sense, but will probably merge in either way just to add another contributor, then if I do start a list of known good/bad likely move it to a different page to make contributions/updates easier.

**Comment by mileswdavis** [comment]
One comment on the "document not working" piece:
My experience has been that more of kit I buy off Amazon DOESN'T have mixed serials than DOES, even if they claim to be FTDI ( both on retail listing and reporting to OS). IE, I personally think that listing what DOES work is less of a chore than what DOESN'T work. Maybe I am just unlucky.

I was not aware that FTPROG was a thing. I may change my tune if what is happening to me is that I am getting real-FTDI chips from lazy vendors rather than knockoffs (who might be lazy as well). I will try this out and see what happens. YAY MANAGING MY OWN SERIAL DATABASE!

**Comment by Pack3tL0ss** [comment]
yeah, just need to be unique for your environment.  If I do keep a list I'll probably just do both.  Most of mine had serials, but I also have a number of dev boards, and most of them have nothing identifying on them (gathered along the way).  Worse case lame adapters can be aliased either by the USB port its plugged into (meaning you would need to keep it in the same port) or by vendorid/productid (if you only have 1 of them).

**Comment by mileswdavis** [comment]
> Worse case lame adapters can be aliased either by the USB port its plugged into (meaning you would need to keep it in the same port) or by vendorid/productid (if you only have 1 of them).

Yuck. But yes, that is what we have been doing for now.

**Pull request merged**
